"""tests/test_contract.py — OpenAPI contract tests via Schemathesis.

Validates that the FastAPI OpenAPI spec is well-formed (always, in-process via
``app.openapi()``), and — when the OpenAPI HTTP surface is exposed
(``expose_api_docs=True``) — that Schemathesis can load it over the ASGI transport and
validate a real response against its declared schema.

Note: ``expose_api_docs`` defaults to False (docs locked down — see the FastAPI() ctor
in app/main.py), which unregisters the ``/openapi.json`` route. The schema itself is
still generated by ``app.openapi()``, so ``test_openapi_schema_is_valid`` always runs;
the Schemathesis smoke test — which drives the ``/openapi.json`` ASGI route via
``from_asgi`` — is skipped unless that surface is exposed.

Run: TESTING=1 PYTHONPATH=/root/availai pytest tests/test_contract.py -v
Or:  schemathesis run --app app.main:app --base-url http://localhost:8000

Called by: pytest
Depends on: schemathesis, app.main
"""

import pytest

try:
    import schemathesis

    HAS_SCHEMATHESIS = True
except ImportError:
    HAS_SCHEMATHESIS = False


def test_openapi_schema_is_valid():
    """The OpenAPI schema generated by FastAPI is valid and parseable.

    Does not depend on Schemathesis or the /openapi.json route — always runs so the
    OpenAPI surface stays covered even when docs are locked down (openapi_url=None).
    """
    from app.main import app

    # app.openapi() generates the schema in-process, independent of route
    # registration — so this works even when openapi_url=None (docs locked down
    # by expose_api_docs=False; see app/main.py FastAPI() ctor).
    schema = app.openapi()
    assert "openapi" in schema
    assert "paths" in schema
    assert len(schema["paths"]) > 0
    # Verify version and metadata from Phase 6A
    assert schema.get("info", {}).get("version")
    assert schema.get("info", {}).get("description")
    # Verify tags are present
    tag_names = [t["name"] for t in schema.get("tags", [])]
    assert "requisitions" in tag_names or "vendors" in tag_names


@pytest.mark.skipif(not HAS_SCHEMATHESIS, reason="schemathesis not installed")
def test_contract_health():
    """Schemathesis loads the ASGI schema and validates GET /health against it.

    Smoke test for the Schemathesis integration: it must be able to load the live
    OpenAPI spec, build a case for a real operation, execute it through the ASGI
    transport, and assert the response conforms to the declared response schema.

    Skipped when ``expose_api_docs`` is False (the default): ``from_asgi`` fetches the
    spec over the ``/openapi.json`` HTTP route, which is unregistered under docs-lockdown.
    Schema well-formedness is still covered by ``test_openapi_schema_is_valid``.
    """
    from app.config import settings
    from app.main import app

    if not settings.expose_api_docs:
        pytest.skip(
            "openapi HTTP route disabled (expose_api_docs=False); "
            "schema validity is covered by test_openapi_schema_is_valid"
        )

    schema = schemathesis.openapi.from_asgi("/openapi.json", app)

    # /health may be excluded from the schema (include_in_schema=False). If so, the
    # successful load + parse above is the smoke test and there is nothing to validate.
    try:
        operation = schema["/health"]["GET"]
    except KeyError:
        return

    case = operation.Case()
    response = case.call()  # ASGI transport is bound by from_asgi()
    case.validate_response(response)
