"""Align UTCDateTime columns to TIMESTAMP WITH TIME ZONE.

Phase 1 (HIGH-DB-2) follow-through: ``UTCDateTime`` now maps uniformly to
``TIMESTAMP WITH TIME ZONE`` (see ``app/database.py``). This migration converts
the backing columns that are still ``timestamp without time zone`` so the schema
self-documents and matches the ORM type. Columns already ``timestamptz`` (those
declared ``UTCDateTime(timezone=True)``) are skipped by the guard.

The conversion interprets existing naive values as UTC (``AT TIME ZONE 'UTC'``),
which is correct because the application has always written UTC. The per-column
``DO`` guard means only ``timestamp without time zone`` columns are touched, so
the migration is idempotent and safe regardless of each column's current state.

NOTE: PostgreSQL-only DDL. Requires a real upgrade -> downgrade -> upgrade cycle
test on PostgreSQL before deploy (the test suite runs on SQLite and does not
exercise this migration).

Revision ID: 085_utcdatetime_tz
Revises: 084_description
Create Date: 2026-06-01
"""

from alembic import op

revision = "085_utcdatetime_tz"
down_revision = "084_description"
branch_labels = None
depends_on = None

# (table, column) for every UTCDateTime-mapped column in the ORM as of this
# revision. Generated by introspecting ``Base.metadata`` against app/models.
_COLUMNS = [
    ("api_sources", "last_success"),
    ("api_sources", "last_error_at"),
    ("api_sources", "last_ping_at"),
    ("api_sources", "last_deep_test_at"),
    ("api_sources", "created_at"),
    ("api_sources", "updated_at"),
    ("column_mapping_cache", "created_at"),
    ("discovery_batches", "started_at"),
    ("discovery_batches", "completed_at"),
    ("discovery_batches", "created_at"),
    ("email_signature_extracts", "created_at"),
    ("email_signature_extracts", "updated_at"),
    ("enrichment_runs", "started_at"),
    ("enrichment_runs", "completed_at"),
    ("enrichment_runs", "created_at"),
    ("ics_worker_status", "last_heartbeat"),
    ("ics_worker_status", "last_search_at"),
    ("ics_worker_status", "updated_at"),
    ("intel_cache", "created_at"),
    ("intel_cache", "expires_at"),
    ("manufacturers", "created_at"),
    ("material_card_audit", "created_at"),
    ("material_cards", "last_searched_at"),
    ("material_cards", "enriched_at"),
    ("material_cards", "deleted_at"),
    ("material_cards", "created_at"),
    ("material_cards", "updated_at"),
    ("nc_worker_status", "last_heartbeat"),
    ("nc_worker_status", "last_search_at"),
    ("nc_worker_status", "updated_at"),
    ("pending_batches", "submitted_at"),
    ("pending_batches", "completed_at"),
    ("processed_messages", "processed_at"),
    ("root_cause_groups", "created_at"),
    ("root_cause_groups", "updated_at"),
    ("sync_logs", "started_at"),
    ("sync_logs", "finished_at"),
    ("sync_logs", "created_at"),
    ("system_config", "updated_at"),
    ("tags", "created_at"),
    ("users", "token_expires_at"),
    ("users", "last_email_scan"),
    ("users", "last_inbox_scan"),
    ("users", "last_contacts_sync"),
    ("users", "m365_last_healthy"),
    ("users", "created_at"),
    ("vendor_cards", "last_enriched_at"),
    ("vendor_cards", "last_contact_at"),
    ("vendor_cards", "engagement_computed_at"),
    ("vendor_cards", "vendor_score_computed_at"),
    ("vendor_cards", "last_activity_at"),
    ("vendor_cards", "material_tags_updated_at"),
    ("vendor_cards", "email_health_computed_at"),
    ("vendor_cards", "deep_enrichment_at"),
    ("vendor_cards", "created_at"),
    ("vendor_cards", "updated_at"),
    ("api_usage_log", "timestamp"),
    ("avail_score_snapshot", "created_at"),
    ("avail_score_snapshot", "updated_at"),
    ("buyer_leaderboard_snapshot", "created_at"),
    ("buyer_leaderboard_snapshot", "updated_at"),
    ("buyer_vendor_stats", "last_contact_at"),
    ("buyer_vendor_stats", "created_at"),
    ("buyer_vendor_stats", "updated_at"),
    ("change_log", "created_at"),
    ("companies", "last_enriched_at"),
    ("companies", "ownership_cleared_at"),
    ("companies", "last_activity_at"),
    ("companies", "material_tags_updated_at"),
    ("companies", "deep_enrichment_at"),
    ("companies", "customer_enrichment_at"),
    ("companies", "created_at"),
    ("companies", "updated_at"),
    ("email_intelligence", "received_at"),
    ("email_intelligence", "created_at"),
    ("enrichment_jobs", "started_at"),
    ("enrichment_jobs", "completed_at"),
    ("enrichment_jobs", "created_at"),
    ("entity_tags", "first_seen_at"),
    ("entity_tags", "last_seen_at"),
    ("graph_subscriptions", "expiration_dt"),
    ("graph_subscriptions", "created_at"),
    ("material_price_snapshots", "recorded_at"),
    ("material_tags", "classified_at"),
    ("material_vendor_history", "first_seen"),
    ("material_vendor_history", "last_seen"),
    ("material_vendor_history", "created_at"),
    ("multiplier_score_snapshot", "created_at"),
    ("multiplier_score_snapshot", "updated_at"),
    ("stock_list_hashes", "first_seen_at"),
    ("stock_list_hashes", "last_seen_at"),
    ("strategic_vendors", "claimed_at"),
    ("strategic_vendors", "last_offer_at"),
    ("strategic_vendors", "expires_at"),
    ("strategic_vendors", "released_at"),
    ("sync_state", "last_sync_at"),
    ("trouble_tickets", "created_at"),
    ("trouble_tickets", "updated_at"),
    ("trouble_tickets", "diagnosed_at"),
    ("trouble_tickets", "resolved_at"),
    ("unified_score_snapshot", "ai_blurb_generated_at"),
    ("unified_score_snapshot", "created_at"),
    ("unified_score_snapshot", "updated_at"),
    ("vendor_contacts", "last_interaction_at"),
    ("vendor_contacts", "first_seen_at"),
    ("vendor_contacts", "last_seen_at"),
    ("vendor_contacts", "score_computed_at"),
    ("vendor_contacts", "ooo_return_date"),
    ("vendor_metrics_snapshot", "created_at"),
    ("vendor_reviews", "created_at"),
    ("verification_group_members", "added_at"),
    ("customer_part_history", "last_purchased_at"),
    ("customer_part_history", "created_at"),
    ("customer_part_history", "updated_at"),
    ("customer_sites", "last_activity_at"),
    ("customer_sites", "ownership_cleared_at"),
    ("customer_sites", "created_at"),
    ("customer_sites", "updated_at"),
    ("enrichment_queue", "reviewed_at"),
    ("enrichment_queue", "created_at"),
    ("proactive_do_not_offer", "created_at"),
    ("prospect_accounts", "claimed_at"),
    ("prospect_accounts", "dismissed_at"),
    ("prospect_accounts", "last_enriched_at"),
    ("prospect_accounts", "created_at"),
    ("prospect_accounts", "updated_at"),
    ("excess_lists", "created_at"),
    ("excess_lists", "updated_at"),
    ("prospect_contacts", "found_at"),
    ("prospect_contacts", "created_at"),
    ("prospect_contacts", "updated_at"),
    ("requisitions", "created_at"),
    ("requisitions", "last_searched_at"),
    ("requisitions", "offers_viewed_at"),
    ("requisitions", "claimed_at"),
    ("requisitions", "updated_at"),
    ("site_contacts", "email_verified_at"),
    ("site_contacts", "last_enriched_at"),
    ("site_contacts", "created_at"),
    ("site_contacts", "updated_at"),
    ("contacts", "status_updated_at"),
    ("contacts", "created_at"),
    ("excess_line_items", "created_at"),
    ("excess_line_items", "updated_at"),
    ("quotes", "sent_at"),
    ("quotes", "followup_alert_sent_at"),
    ("quotes", "result_at"),
    ("quotes", "created_at"),
    ("quotes", "updated_at"),
    ("requirements", "created_at"),
    ("requirements", "last_searched_at"),
    ("requisition_attachments", "created_at"),
    ("bid_solicitations", "response_received_at"),
    ("bid_solicitations", "sent_at"),
    ("bid_solicitations", "created_at"),
    ("bids", "created_at"),
    ("bids", "updated_at"),
    ("buy_plans_v3", "approved_at"),
    ("buy_plans_v3", "so_verified_at"),
    ("buy_plans_v3", "submitted_at"),
    ("buy_plans_v3", "completed_at"),
    ("buy_plans_v3", "cancelled_at"),
    ("buy_plans_v3", "halted_at"),
    ("buy_plans_v3", "token_expires_at"),
    ("buy_plans_v3", "created_at"),
    ("buy_plans_v3", "updated_at"),
    ("ics_search_queue", "last_searched_at"),
    ("ics_search_queue", "created_at"),
    ("ics_search_queue", "updated_at"),
    ("knowledge_entries", "expires_at"),
    ("knowledge_entries", "nudged_at"),
    ("knowledge_entries", "delivered_at"),
    ("knowledge_entries", "created_at"),
    ("knowledge_entries", "updated_at"),
    ("nc_search_queue", "last_searched_at"),
    ("nc_search_queue", "created_at"),
    ("nc_search_queue", "updated_at"),
    ("proactive_offers", "sent_at"),
    ("proactive_offers", "converted_at"),
    ("proactive_offers", "created_at"),
    ("requirement_attachments", "created_at"),
    ("requisition_tasks", "due_at"),
    ("requisition_tasks", "completed_at"),
    ("requisition_tasks", "created_at"),
    ("requisition_tasks", "updated_at"),
    ("sightings", "source_searched_at"),
    ("sightings", "created_at"),
    ("sourcing_leads", "source_first_seen_at"),
    ("sourcing_leads", "source_last_seen_at"),
    ("sourcing_leads", "vendor_safety_last_checked_at"),
    ("sourcing_leads", "last_buyer_action_at"),
    ("sourcing_leads", "created_at"),
    ("sourcing_leads", "updated_at"),
    ("vendor_responses", "received_at"),
    ("vendor_responses", "created_at"),
    ("vendor_sighting_summary", "updated_at"),
    ("vendor_sighting_summary", "newest_sighting_at"),
    ("activity_log", "dismissed_at"),
    ("activity_log", "occurred_at"),
    ("activity_log", "quality_assessed_at"),
    ("activity_log", "created_at"),
    ("ics_search_log", "searched_at"),
    ("lead_evidence", "observed_at"),
    ("lead_evidence", "created_at"),
    ("lead_feedback_events", "created_at"),
    ("nc_search_log", "searched_at"),
    ("offers", "promoted_at"),
    ("offers", "created_at"),
    ("offers", "updated_at"),
    ("offers", "approved_at"),
    ("offers", "selected_at"),
    ("offers", "expires_at"),
    ("offers", "reconfirmed_at"),
    ("proactive_throttle", "last_offered_at"),
    ("buy_plan_lines", "estimated_ship_date"),
    ("buy_plan_lines", "po_confirmed_at"),
    ("buy_plan_lines", "po_verified_at"),
    ("buy_plan_lines", "created_at"),
    ("buy_plan_lines", "updated_at"),
    ("offer_attachments", "created_at"),
    ("proactive_matches", "customer_last_purchased_at"),
    ("proactive_matches", "created_at"),
]


def _convert(target_type: str, source_type: str) -> None:
    """Convert every listed column from ``source_type`` to ``target_type``.

    Guarded per-column so only columns currently of ``source_type`` are altered;
    columns already at ``target_type`` (or absent) are left untouched.
    """
    for table, column in _COLUMNS:
        op.execute(
            f"""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = '{table}'
                      AND column_name = '{column}'
                      AND data_type = '{source_type}'
                ) THEN
                    EXECUTE 'ALTER TABLE {table} ALTER COLUMN {column} '
                         || 'TYPE {target_type} USING {column} AT TIME ZONE ''UTC''';
                END IF;
            END $$;
            """
        )


def upgrade() -> None:
    _convert("timestamptz", "timestamp without time zone")


def downgrade() -> None:
    _convert("timestamp without time zone", "timestamp with time zone")
