"""Add excess inventory and bid collection tables.

Revision ID: 29a41f5a248c
Revises: 540b2a375edd
Create Date: 2026-03-19 22:38:20.511736
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29a41f5a248c"
down_revision: Union[str, None] = "540b2a375edd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "excess_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("customer_site_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("source_filename", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("total_line_items", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["customer_site_id"], ["customer_sites.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_excess_lists_company", "excess_lists", ["company_id"], unique=False)
    op.create_index("ix_excess_lists_owner", "excess_lists", ["owner_id"], unique=False)
    op.create_index("ix_excess_lists_status", "excess_lists", ["status"], unique=False)
    op.create_table(
        "excess_line_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("excess_list_id", sa.Integer(), nullable=False),
        sa.Column("part_number", sa.String(length=100), nullable=False),
        sa.Column("manufacturer", sa.String(length=255), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("date_code", sa.String(length=50), nullable=True),
        sa.Column("condition", sa.String(length=50), nullable=True),
        sa.Column("asking_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("market_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("demand_score", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["excess_list_id"], ["excess_lists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_excess_line_items_list", "excess_line_items", ["excess_list_id"], unique=False)
    op.create_index(op.f("ix_excess_line_items_part_number"), "excess_line_items", ["part_number"], unique=False)
    op.create_index("ix_excess_line_items_status", "excess_line_items", ["status"], unique=False)
    op.create_table(
        "bid_solicitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("excess_line_item_id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("sent_by", sa.Integer(), nullable=False),
        sa.Column("email_track_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["excess_line_item_id"], ["excess_line_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sent_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_bid_solicitations_contact", "bid_solicitations", ["contact_id"], unique=False)
    op.create_index("ix_bid_solicitations_line_item", "bid_solicitations", ["excess_line_item_id"], unique=False)
    op.create_table(
        "bids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("excess_line_item_id", sa.Integer(), nullable=False),
        sa.Column("bidder_company_id", sa.Integer(), nullable=True),
        sa.Column("bidder_vendor_card_id", sa.Integer(), nullable=True),
        sa.Column("bidder_contact_id", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("quantity_wanted", sa.Integer(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["bidder_company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["bidder_vendor_card_id"], ["vendor_cards.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["excess_line_item_id"], ["excess_line_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_bids_company", "bids", ["bidder_company_id"], unique=False)
    op.create_index("ix_bids_line_item", "bids", ["excess_line_item_id"], unique=False)
    op.create_index("ix_bids_status", "bids", ["status"], unique=False)
    op.create_index("ix_bids_vendor_card", "bids", ["bidder_vendor_card_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bids_vendor_card", table_name="bids")
    op.drop_index("ix_bids_status", table_name="bids")
    op.drop_index("ix_bids_line_item", table_name="bids")
    op.drop_index("ix_bids_company", table_name="bids")
    op.drop_table("bids")
    op.drop_index("ix_bid_solicitations_line_item", table_name="bid_solicitations")
    op.drop_index("ix_bid_solicitations_contact", table_name="bid_solicitations")
    op.drop_table("bid_solicitations")
    op.drop_index("ix_excess_line_items_status", table_name="excess_line_items")
    op.drop_index(op.f("ix_excess_line_items_part_number"), table_name="excess_line_items")
    op.drop_index("ix_excess_line_items_list", table_name="excess_line_items")
    op.drop_table("excess_line_items")
    op.drop_index("ix_excess_lists_status", table_name="excess_lists")
    op.drop_index("ix_excess_lists_owner", table_name="excess_lists")
    op.drop_index("ix_excess_lists_company", table_name="excess_lists")
    op.drop_table("excess_lists")
    # ### end Alembic commands ###
