"""Add screenshot_path ai_summary root_cause_groups.

Revision ID: 5c6736d6381f
Revises: a4df7e282b71
Create Date: 2026-03-21 02:56:41.744311
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c6736d6381f"
down_revision: Union[str, None] = "a4df7e282b71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "root_cause_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("offers", sa.Column("excess_line_item_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "offers_excess_line_item_id_fkey",
        "offers",
        "excess_line_items",
        ["excess_line_item_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("trouble_tickets", sa.Column("screenshot_path", sa.String(length=255), nullable=True))
    op.add_column("trouble_tickets", sa.Column("ai_summary", sa.Text(), nullable=True))
    op.add_column("trouble_tickets", sa.Column("root_cause_group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "trouble_tickets_root_cause_group_id_fkey",
        "trouble_tickets",
        "root_cause_groups",
        ["root_cause_group_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("trouble_tickets_root_cause_group_id_fkey", "trouble_tickets", type_="foreignkey")
    op.drop_column("trouble_tickets", "root_cause_group_id")
    op.drop_column("trouble_tickets", "ai_summary")
    op.drop_column("trouble_tickets", "screenshot_path")
    op.drop_constraint("offers_excess_line_item_id_fkey", "offers", type_="foreignkey")
    op.drop_column("offers", "excess_line_item_id")
    op.drop_table("root_cause_groups")
    # ### end Alembic commands ###
