"""Add vendor_card_id and pre-aggregated fields to vendor_sighting_summary.

Revision ID: 838cd7ddccf1
Revises: d2bea118f720
Create Date: 2026-03-25 04:29:17.738913
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "838cd7ddccf1"
down_revision: str | None = "d2bea118f720"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_activity_created_at", "activity_log", ["created_at"], unique=False, if_not_exists=True)
    op.create_index(
        "ix_excess_line_items_demand",
        "excess_line_items",
        ["demand_match_count", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_excess_line_items_pn_status",
        "excess_line_items",
        ["part_number", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_constraint(op.f("manufacturers_canonical_name_key"), "manufacturers", type_="unique")
    op.create_index("ix_quote_lines_offer", "quote_lines", ["offer_id"], unique=False, if_not_exists=True)
    op.drop_index(op.f("ix_reqmt_attachments_reqmt_id"), table_name="requirement_attachments", if_exists=True)
    op.create_index(
        op.f("ix_requirement_attachments_requirement_id"),
        "requirement_attachments",
        ["requirement_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(op.f("ix_requirements_manufacturer"), table_name="requirements", if_exists=True)
    op.drop_index(op.f("ix_requirements_primary_mpn"), table_name="requirements", if_exists=True)
    op.drop_index(
        op.f("ix_requirements_subs_trgm"),
        table_name="requirements",
        postgresql_ops={"substitutes_text": "gin_trgm_ops"},
        postgresql_using="gin",
        if_exists=True,
    )
    op.drop_index(op.f("ix_req_attachments_req_id"), table_name="requisition_attachments", if_exists=True)
    op.create_index(
        op.f("ix_requisition_attachments_requisition_id"),
        "requisition_attachments",
        ["requisition_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_vendor_cards_active",
        "vendor_cards",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("is_blacklisted IS false"),
        if_not_exists=True,
    )
    op.create_index(
        "ix_vr_received_status", "vendor_responses", ["received_at", "status"], unique=False, if_not_exists=True
    )
    op.add_column("vendor_sighting_summary", sa.Column("vendor_card_id", sa.Integer(), nullable=True))
    op.execute(
        "ALTER TABLE vendor_sighting_summary ADD COLUMN IF NOT EXISTS newest_sighting_at TIMESTAMP WITHOUT TIME ZONE"
    )
    op.add_column("vendor_sighting_summary", sa.Column("best_lead_time_days", sa.Integer(), nullable=True))
    op.add_column("vendor_sighting_summary", sa.Column("min_moq", sa.Integer(), nullable=True))
    op.add_column(
        "vendor_sighting_summary", sa.Column("has_contact_info", sa.Boolean(), server_default="false", nullable=True)
    )
    op.create_index(
        "ix_vss_vendor_card", "vendor_sighting_summary", ["vendor_card_id"], unique=False, if_not_exists=True
    )
    op.create_index(
        "ix_vss_vendor_req",
        "vendor_sighting_summary",
        ["vendor_name", "requirement_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_foreign_key(
        None, "vendor_sighting_summary", "vendor_cards", ["vendor_card_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vendor_sighting_summary", type_="foreignkey")
    op.drop_index("ix_vss_vendor_req", table_name="vendor_sighting_summary", if_exists=True)
    op.drop_index("ix_vss_vendor_card", table_name="vendor_sighting_summary", if_exists=True)
    op.execute("ALTER TABLE IF EXISTS vendor_sighting_summary DROP COLUMN IF EXISTS has_contact_info")
    op.execute("ALTER TABLE IF EXISTS vendor_sighting_summary DROP COLUMN IF EXISTS min_moq")
    op.execute("ALTER TABLE IF EXISTS vendor_sighting_summary DROP COLUMN IF EXISTS best_lead_time_days")
    op.execute("ALTER TABLE IF EXISTS vendor_sighting_summary DROP COLUMN IF EXISTS newest_sighting_at")
    op.execute("ALTER TABLE IF EXISTS vendor_sighting_summary DROP COLUMN IF EXISTS vendor_card_id")
    op.drop_index("ix_vr_received_status", table_name="vendor_responses", if_exists=True)
    op.drop_index(
        "ix_vendor_cards_active",
        table_name="vendor_cards",
        postgresql_where=sa.text("is_blacklisted IS false"),
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_requisition_attachments_requisition_id"), table_name="requisition_attachments", if_exists=True
    )
    op.create_index(
        op.f("ix_req_attachments_req_id"),
        "requisition_attachments",
        ["requisition_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_requirements_subs_trgm"),
        "requirements",
        ["substitutes_text"],
        unique=False,
        postgresql_ops={"substitutes_text": "gin_trgm_ops"},
        postgresql_using="gin",
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_requirements_primary_mpn"), "requirements", ["primary_mpn"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("ix_requirements_manufacturer"), "requirements", ["manufacturer"], unique=False, if_not_exists=True
    )
    op.drop_index(
        op.f("ix_requirement_attachments_requirement_id"), table_name="requirement_attachments", if_exists=True
    )
    op.create_index(
        op.f("ix_reqmt_attachments_reqmt_id"),
        "requirement_attachments",
        ["requirement_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index("ix_quote_lines_offer", table_name="quote_lines", if_exists=True)
    op.create_unique_constraint(
        op.f("manufacturers_canonical_name_key"),
        "manufacturers",
        ["canonical_name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index("ix_excess_line_items_pn_status", table_name="excess_line_items", if_exists=True)
    op.drop_index("ix_excess_line_items_demand", table_name="excess_line_items", if_exists=True)
    op.drop_index("ix_activity_created_at", table_name="activity_log", if_exists=True)
    # ### end Alembic commands ###
