"""Add description, package_type, revision to requirements.

Revision ID: a23a31ac0a02
Revises: 70b4dce3cf67
Create Date: 2026-03-26 16:28:41.964172
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a23a31ac0a02"
down_revision: str | None = "70b4dce3cf67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requirements", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("requirements", sa.Column("package_type", sa.String(length=100), nullable=True))
    op.add_column("requirements", sa.Column("revision", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE IF EXISTS requirements DROP COLUMN IF EXISTS revision")
    op.execute("ALTER TABLE IF EXISTS requirements DROP COLUMN IF EXISTS package_type")
    op.execute("ALTER TABLE IF EXISTS requirements DROP COLUMN IF EXISTS description")
    # ### end Alembic commands ###
