"""Add description, package_type, revision to requirements.

Revision ID: a23a31ac0a02
Revises: 70b4dce3cf67
Create Date: 2026-03-26 16:28:41.964172
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a23a31ac0a02"
down_revision: Union[str, None] = "70b4dce3cf67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE requirements ADD COLUMN IF NOT EXISTS description TEXT")
    op.execute("ALTER TABLE requirements ADD COLUMN IF NOT EXISTS package_type VARCHAR(100)")
    op.execute("ALTER TABLE requirements ADD COLUMN IF NOT EXISTS revision VARCHAR(100)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE requirements DROP COLUMN IF EXISTS revision")
    op.execute("ALTER TABLE requirements DROP COLUMN IF EXISTS package_type")
    op.execute("ALTER TABLE requirements DROP COLUMN IF EXISTS description")
    # ### end Alembic commands ###
