"""add_resolved_via_spec_code_to_queue_tables.

Adds ``resolved_via_spec_code`` lineage column to ``ics_search_queue`` and
``nc_search_queue`` to record spec-code provenance on each queue row. Also
drops the legacy ``requirement_id`` UNIQUE
constraints on both queue tables and replaces them with a composite
``(requirement_id, normalized_mpn)`` UNIQUE — dedup is keyed on that pair so
the spec-code resolver can enqueue multiple AVL MPNs per requirement while a
DB constraint still rejects true duplicates (the in-Python check in
``QueueManager.enqueue_search`` loses to concurrent enqueues otherwise).

Revision ID: cf06dcdb7839
Revises: 9868c839df65
Create Date: 2026-05-27
"""

import sqlalchemy as sa

from alembic import op

revision = "cf06dcdb7839"
down_revision = "9868c839df65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "ics_search_queue",
        sa.Column("resolved_via_spec_code", sa.String(64), nullable=True),
    )
    op.add_column(
        "nc_search_queue",
        sa.Column("resolved_via_spec_code", sa.String(64), nullable=True),
    )

    # Drop the legacy per-requirement UNIQUE constraint so the spec-code
    # resolver can enqueue multiple (requirement_id, normalized_mpn) rows.
    # Constraint names were assigned by PostgreSQL when the column was
    # created with ``unique=True`` — use ``IF EXISTS`` so the migration is
    # tolerant of either the autogenerated name or a hand-named constraint.
    op.execute("ALTER TABLE ics_search_queue DROP CONSTRAINT IF EXISTS ics_search_queue_requirement_id_key")
    op.execute("ALTER TABLE nc_search_queue DROP CONSTRAINT IF EXISTS nc_search_queue_requirement_id_key")

    # Replace it with the composite (requirement_id, normalized_mpn) UNIQUE so
    # the multi-AVL enqueue is allowed but true duplicates are still rejected
    # at the DB layer (matches the model __table_args__).
    op.create_unique_constraint(
        "uq_ics_queue_requirement_mpn",
        "ics_search_queue",
        ["requirement_id", "normalized_mpn"],
    )
    op.create_unique_constraint(
        "uq_nc_queue_requirement_mpn",
        "nc_search_queue",
        ["requirement_id", "normalized_mpn"],
    )


def downgrade() -> None:
    # Drop the composite UNIQUE first.
    op.drop_constraint("uq_nc_queue_requirement_mpn", "nc_search_queue", type_="unique")
    op.drop_constraint("uq_ics_queue_requirement_mpn", "ics_search_queue", type_="unique")

    # Restore the per-requirement UNIQUE constraint. If duplicate rows now
    # exist (because the resolver enqueued multiple AVL MPNs for the same
    # requirement), this will fail — operator must clean up duplicates
    # before downgrading.
    op.create_unique_constraint(
        "nc_search_queue_requirement_id_key",
        "nc_search_queue",
        ["requirement_id"],
    )
    op.create_unique_constraint(
        "ics_search_queue_requirement_id_key",
        "ics_search_queue",
        ["requirement_id"],
    )

    op.drop_column("nc_search_queue", "resolved_via_spec_code")
    op.drop_column("ics_search_queue", "resolved_via_spec_code")
