"""add_resolved_via_spec_code_to_queue_tables.

Adds ``resolved_via_spec_code`` lineage column to ``ics_search_queue`` and
``nc_search_queue`` so the workers can propagate spec-code provenance onto
the sightings they create. Also drops the legacy ``requirement_id`` UNIQUE
constraints on both queue tables — dedup is now keyed on
``(requirement_id, normalized_mpn)`` at the application layer so the
spec-code resolver can enqueue multiple AVL MPNs per requirement.

Revision ID: cf06dcdb7839
Revises: 9868c839df65
Create Date: 2026-05-27
"""

import sqlalchemy as sa

from alembic import op

revision = "cf06dcdb7839"
down_revision = "9868c839df65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "ics_search_queue",
        sa.Column("resolved_via_spec_code", sa.String(64), nullable=True),
    )
    op.add_column(
        "nc_search_queue",
        sa.Column("resolved_via_spec_code", sa.String(64), nullable=True),
    )

    # Drop the legacy per-requirement UNIQUE constraint so the spec-code
    # resolver can enqueue multiple (requirement_id, normalized_mpn) rows.
    # Constraint names were assigned by PostgreSQL when the column was
    # created with ``unique=True`` — use ``IF EXISTS`` so the migration is
    # tolerant of either the autogenerated name or a hand-named constraint.
    op.execute("ALTER TABLE ics_search_queue DROP CONSTRAINT IF EXISTS ics_search_queue_requirement_id_key")
    op.execute("ALTER TABLE nc_search_queue DROP CONSTRAINT IF EXISTS nc_search_queue_requirement_id_key")


def downgrade() -> None:
    # Restore the per-requirement UNIQUE constraint. If duplicate rows now
    # exist (because the resolver enqueued multiple AVL MPNs for the same
    # requirement), this will fail — operator must clean up duplicates
    # before downgrading.
    op.create_unique_constraint(
        "nc_search_queue_requirement_id_key",
        "nc_search_queue",
        ["requirement_id"],
    )
    op.create_unique_constraint(
        "ics_search_queue_requirement_id_key",
        "ics_search_queue",
        ["requirement_id"],
    )

    op.drop_column("nc_search_queue", "resolved_via_spec_code")
    op.drop_column("ics_search_queue", "resolved_via_spec_code")
