"""Add material_price_snapshots table.

Revision ID: f3fbddb04947
Revises: a513288799de
Create Date: 2026-03-19 03:37:52.510626
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3fbddb04947"
down_revision: Union[str, None] = "a513288799de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_price_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("material_card_id", sa.Integer(), nullable=False),
        sa.Column("vendor_name", sa.String(length=200), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["material_card_id"],
            ["material_cards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_material_price_snapshots_material_card_id"),
        "material_price_snapshots",
        ["material_card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_price_snapshots_recorded_at"), "material_price_snapshots", ["recorded_at"], unique=False
    )
    op.create_index(
        "ix_price_snap_card_time", "material_price_snapshots", ["material_card_id", "recorded_at"], unique=False
    )
    # NOTE: Trigram indexes (ix_*_trgm) are managed by startup.py, not Alembic. Do not drop them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_snap_card_time", table_name="material_price_snapshots")
    op.drop_index(op.f("ix_material_price_snapshots_recorded_at"), table_name="material_price_snapshots")
    op.drop_index(op.f("ix_material_price_snapshots_material_card_id"), table_name="material_price_snapshots")
    op.drop_table("material_price_snapshots")
    # ### end Alembic commands ###
